### ISSUE TITLE
Failing to parse any encrypted private key PEM with Asn1 Error Tag Unknown 

### ISSUE THREAD

**Issue by xoryouyou** [RustCrypto/formats#1105]
Hi,
I am trying to decrypt an encrypted private key stored in PEM and am out of ideas where the problem comes from.

During my attempts I ran into the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on 
an `Err` value: Asn1(Error { kind: TagUnknown { byte: 45 }, position: None })', src/main.rs:8:94
```
Originally I am trying to load an P-256 key and not an ED25519 but since there are no encrypted P-256 examples I am using the ED25519 files which are resulting in the same error.

To validate that I've got a proper PEM file and the error is not on my side I am trying to load one of your example PEM files.
This one: [examples/ed25519-encpriv-aes256-pbkdf2-sha256.pem](pkcs8/tests/examples/ed25519-encpriv-aes256-pbkdf2-sha256.pem)

`Cargo.toml`:

```toml
[package]
name = "pem_parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkcs8 = { version = "0.10.2", features = ["pem", "encryption", "pkcs5"] }

```

`main.rs`:
```rust
use pkcs8::EncryptedPrivateKeyInfo;

fn main() {
    const ED25519_PEM_AES256_PBKDF2_SHA256_EXAMPLE: &[u8] = include_bytes!("ed25519-encpriv-aes256-pbkdf2-sha256.pem");
    const PASSWORD: &[u8] = b"hunter42"; 


    let enc_pk = EncryptedPrivateKeyInfo::try_from(ED25519_PEM_AES256_PBKDF2_SHA256_EXAMPLE).unwrap();
    let pk = enc_pk.decrypt(PASSWORD).unwrap();
}

```

For some reason I am not able to load any key from PEM neither your example keys nor my own which are made with openssl.

Also I've noticed that `cargo test` does not execute the `encrypted_private_key.rs`  tests

`cargo test`
```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/encrypted_private_key.rs (.../target/debug/deps/encrypted_private_key-8c37dd4e5cfe8863)

running 0 tests
```

Am I missing something obvious ? :)
